Update root_environment.yml
Dropping the following due to the following error when attempting to create the `env`:

```bash
PackagesNotFoundError: The following packages are not available from current channels:

  - sys
  - pickle
  - os
  - datetime
```